import streamlit as st
from groq import Groq
import sympy as sp
from datetime import datetime
import urllib.parse
import numpy as np
from scipy.io.wavfile import write
import io

st.set_page_config(page_title="JARVIS ULTIMATE", page_icon="🤖", layout="wide")
st.title("🤖 JARVIS ULTIMATE")
st.caption("Chat | Image | Video | Maths | Music - All in One")

GROQ_KEY = st.secrets.get("GROQ_KEY", None) if hasattr(st, "secrets") else None
if not GROQ_KEY:
    GROQ_KEY = st.sidebar.text_input("Groq API Key", type="password")

    client = Groq(api_key=GROQ_KEY) if GROQ_KEY else None

    if "history" not in st.session_state:
        st.session_state.history = []

        SYSTEM_PROMPT = "You are JARVIS ULTIMATE. Reply in same language as user. Date: {date}"

        tab1, tab2, tab3, tab4, tab5 = st.tabs(["💬 Chat", "🎨 Image", "🎬 Video", "🧮 Maths", "🎵 Music"])

        with tab1:
            for m in st.session_state.history:
                    with st.chat_message(m["role"]):
                                st.markdown(m["content"])
                                    if p := st.chat_input("Boss pucho..."):
                                            st.session_state.history.append({"role": "user", "content": p})
                                                    with st.chat_message("user"):
                                                                st.markdown(p)
                                                                        if client:
                                                                                    with st.chat_message("assistant"):
                                                                                                    r = client.chat.completions.create(
                                                                                                                        model="openai/gpt-oss-20b",
                                                                                                                                            messages=[{"role": "system", "content": SYSTEM_PROMPT.format(date=datetime.now().strftime("%d-%m-%Y"))}] + st.session_state.history
                                                                                                                                                            )
                                                                                                                                                                            ans = r.choices[0].message.content
                                                                                                                                                                                            st.markdown(ans)
                                                                                                                                                                                                            st.session_state.history.append({"role": "assistant", "content": ans})

                                                                                                                                                                                                            with tab2:
                                                                                                                                                                                                                st.subheader("🎨 Image Generator")
                                                                                                                                                                                                                    pr = st.text_input("Image prompt", placeholder="Iron man in village")
                                                                                                                                                                                                                        if st.button("Generate Image", key="img"):
                                                                                                                                                                                                                                if pr:
                                                                                                                                                                                                                                            url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote(pr)}?width=1024&height=1024&nologo=true"
                                                                                                                                                                                                                                                        st.image(url)

                                                                                                                                                                                                                                                        with tab3:
                                                                                                                                                                                                                                                            st.subheader("🎬 Video Script")
                                                                                                                                                                                                                                                                vp = st.text_input("Video prompt", placeholder="Drone shot")
                                                                                                                                                                                                                                                                    if st.button("Generate Script", key="vid"):
                                                                                                                                                                                                                                                                            if vp and client:
                                                                                                                                                                                                                                                                                        vr = client.chat.completions.create(model="openai/gpt-oss-20b", messages=[{"role": "user", "content": vp}])
                                                                                                                                                                                                                                                                                                    st.info(vr.choices[0].message.content)

                                                                                                                                                                                                                                                                                                    with tab4:
                                                                                                                                                                                                                                                                                                        st.subheader("🧮 Maths Solver")
                                                                                                                                                                                                                                                                                                            mi = st.text_input("Maths", placeholder="integrate x^2")
                                                                                                                                                                                                                                                                                                                if st.button("Solve", key="math"):
                                                                                                                                                                                                                                                                                                                        if mi:
                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                    st.success(f"Answer: {sp.simplify(sp.sympify(mi))}")
                                                                                                                                                                                                                                                                                                                                                                except:
                                                                                                                                                                                                                                                                                                                                                                                if client:
                                                                                                                                                                                                                                                                                                                                                                                                    mr = client.chat.completions.create(model="openai/gpt-oss-20b", messages=[{"role": "user", "content": mi}])
                                                                                                                                                                                                                                                                                                                                                                                                                        st.markdown(mr.choices[0].message.content)

                                                                                                                                                                                                                                                                                                                                                                                                                        with tab5:
                                                                                                                                                                                                                                                                                                                                                                                                                            st.subheader("🎵 Music Generator")
                                                                                                                                                                                                                                                                                                                                                                                                                                mood = st.selectbox("Mood chuno", ["Happy", "Sad", "Dramatic", "Suspense", "Victory", "Relax"])
                                                                                                                                                                                                                                                                                                                                                                                                                                    duration = st.slider("Duration", 3, 20, 8)
                                                                                                                                                                                                                                                                                                                                                                                                                                        custom = st.text_input("Custom mood (optional)", placeholder="Like romantic, energetic")

                                                                                                                                                                                                                                                                                                                                                                                                                                            def make_music(m, dur):
                                                                                                                                                                                                                                                                                                                                                                                                                                                    sr = 44100
                                                                                                                                                                                                                                                                                                                                                                                                                                                            t = np.linspace(0, dur, int(sr * dur), False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if m.lower() == "happy":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                freqs = [262, 330, 392, 523]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif m.lower() == "sad":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    freqs = [220, 261, 329]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif m.lower() == "dramatic":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        freqs = [220, 277, 329, 440]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            freqs = [261, 329, 392, 440]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    music = np.zeros_like(t)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i, f in enumerate(freqs):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        music += np.sin(2 * np.pi * f * t) * np.exp(-t/dur) * (1/(i+1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                music = (music / np.max(np.abs(music)) * 32767).astype(np.int16)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        buf = io.BytesIO()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                write(buf, sr, music)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return buf.getvalue()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if st.button("Generate Music", type="primary"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final = custom if custom else mood
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            audio = make_music(final, duration)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.audio(audio, format='audio/wav')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.download_button("Download Music", data=audio, file_name=f"{final}.wav", mime="audio/wav")