import streamlit as st
from groq import Groq
import sympy as sp
from datetime import datetime
import urllib.parse
import re

st.set_page_config(page_title="JARVIS ULTIMATE", page_icon="🤖", layout="wide")
st.title("🤖 JARVIS ULTIMATE")
st.caption("Image | Video | Maths | Chat - All in One")

GROQ_KEY = None
try:
    GROQ_KEY = st.secrets["GROQ_KEY"]
    except Exception:
        GROQ_KEY = None

        if not GROQ_KEY:
            GROQ_KEY = st.sidebar.text_input("Groq API Key", type="password")

            client = None
            if GROQ_KEY:
                try:
                        client = Groq(api_key=GROQ_KEY)
                            except Exception:
                                    client = None

                                    if "history" not in st.session_state:
                                        st.session_state.history = []

                                        SYSTEM_PROMPT = """
                                        You are JARVIS ULTIMATE made by Boss devil-01-01.
                                        STRICT LANGUAGE RULE: Reply in SAME language and SAME script as user's last message only. Never mix. English->English, Roman Hindi->Roman Hindi, Devanagari Hindi->Devanagari Hindi.
                                        You are expert in Maths, Coding, Prediction, Image prompt, Video script.
                                        Date: {date}
                                        """

                                        tab1, tab2, tab3, tab4 = st.tabs(["💬 Chat", "🎨 Image", "🎬 Video", "🧮 Maths"])

                                        with tab1:
                                            for m in st.session_state.history:
                                                    with st.chat_message(m["role"]):
                                                                st.markdown(m["content"])
                                                                    if prompt := st.chat_input("Boss pucho kuch bhi..."):
                                                                            st.session_state.history.append({"role": "user", "content": prompt})
                                                                                    with st.chat_message("user"):
                                                                                                st.markdown(prompt)
                                                                                                        if client:
                                                                                                                    with st.chat_message("assistant"):
                                                                                                                                    try:
                                                                                                                                                        r = client.chat.completions.create(
                                                                                                                                                                                model="openai/gpt-oss-20b",
                                                                                                                                                                                                        messages=[{"role": "system", "content": SYSTEM_PROMPT.format(date=datetime.now().strftime("%d-%m-%Y"))}, *st.session_state.history]
                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                ans = r.choices[0].message.content
                                                                                                                                                                                                                                                                    st.markdown(ans)
                                                                                                                                                                                                                                                                                        st.session_state.history.append({"role": "assistant", "content": ans})
                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                            st.error(str(e))
                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                st.warning("Groq Key daalo sidebar me")

                                                                                                                                                                                                                                                                                                                                                with tab2:
                                                                                                                                                                                                                                                                                                                                                    st.subheader("🎨 Free Image Generator")
                                                                                                                                                                                                                                                                                                                                                        p = st.text_input("Image prompt:", placeholder="Iron man in Pothia village, 8k")
                                                                                                                                                                                                                                                                                                                                                            if st.button("Generate Image", type="primary"):
                                                                                                                                                                                                                                                                                                                                                                    if p:
                                                                                                                                                                                                                                                                                                                                                                                url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote(p)}?width=1024&height=1024&nologo=true"
                                                                                                                                                                                                                                                                                                                                                                                            st.image(url, caption=p)
                                                                                                                                                                                                                                                                                                                                                                                                        st.code(url)

                                                                                                                                                                                                                                                                                                                                                                                                        with tab3:
                                                                                                                                                                                                                                                                                                                                                                                                            st.subheader("🎬 Video Prompt to Script")
                                                                                                                                                                                                                                                                                                                                                                                                                vp = st.text_input("Video prompt:", placeholder="Drone shot of Bihar in rain")
                                                                                                                                                                                                                                                                                                                                                                                                                    if st.button("Generate Video Script", type="primary"):
                                                                                                                                                                                                                                                                                                                                                                                                                            if vp and client:
                                                                                                                                                                                                                                                                                                                                                                                                                                        vr = client.chat.completions.create(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        model="openai/gpt-oss-20b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        messages=[{"role": "system", "content": "You are video prompt expert. Create detailed cinematic prompt."}, {"role": "user", "content": vp}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.info(vr.choices[0].message.content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown("Free tools: [RunwayML](https://app.runwayml.com/) | [Pika.art](https://pika.art)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.warning("Prompt likho aur Groq Key check karo")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with tab4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.subheader("🧮 Maths Solver")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mi = st.text_input("Maths likho:", placeholder="integrate x^2, 2+2*10, solve x^2-4=0")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if st.button("Solve", type="primary"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if mi:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                low = mi.lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if "integrate" in low:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f = low.replace("integrate", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res = sp.integrate(sp.sympify(f))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.latex(r"\int " + sp.latex(sp.sympify(f)) + " = " + sp.latex(res) + " + C")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.success(f"Answer: {res} + C")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif "derivative" in low or "differentiate" in low:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f = re.sub(r'derivative|differentiate|of', '', low)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res = sp.diff(sp.sympify(f))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.success(f"Answer: {res}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res = sp.sympify(mi)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success(f"Answer: {sp.simplify(res)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if client:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mr = client.chat.completions.create(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model="openai/gpt-oss-20b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages=[{"role": "system", "content": "Solve maths step by step, same language as user"}, {"role": "user", "content": mi}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown(mr.choices[0].message.content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.error(str(e))